name: ci test

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:

    - name: change permission
      run: chmod 777 -R /home/runner/work/crud_test_with_nodejsExpress_atlas_aws/
    
    - uses: actions/checkout@v1
    - name: Run Jest
      uses: stefanoeb/jest-action@1.0.3
      with:
        jestArgs: "--jsdom"
