name: Node.js CI/CD

on:
  push:
    branches: [ main, section_3 ]
  
jobs:
  build:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [16.x]

    steps:
      - uses: actions/checkout@v3
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}
      - run: npm ci
      # for install related modules for jest test
      - run: npm install
      - run: npm run build --if-present
      - run: npm run test_mongo

      - name: checkout the files
        uses: actions/checkout@v3

      - name: Install Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '16.x'
      - name: install npm dependencies
        run: npm install
      - name: run build test
        run: npm run build --if-present

    
      # - name: Prepare SSH to work with the remote server
      #   run: |
      #     cd ~ && mkdir .ssh && cd .ssh && echo '54.244.129.102' > ~/.ssh/known_hosts
          


      - name: deploy to ec2
        uses: easingthemes/ssh-deploy@main
        env:
          # SSH_PRIVATE_KEY: ${{ Secrets.SERVER_SSH_KEY }}
          # REMOTE_HOST: ${{ Secrets.REMOTE_HOST }}
          # REMOTE_USER: ${{ Secrets.REMOTE_USER }}
          # TARGET: ${{ Secrets.REMOTE_TARGET }}
          
          SSH_PRIVATE_KEY: ${{Secrets.NTOUSE2022_SSHPRIKEY}}
          REMOTE_HOST: '54.244.129.102'
          REMOTE_USER: ${{ Secrets.REMOTE_USER }}
          TARGET: '/home/ubuntu/section_3'
          run: chmod 777 -R /home/ubuntu/crud_test

          