
# variables
secrets:
  SERVER_SSH_KEY: "-----BEGIN OPENSSH PRIVATE KEY-----
b3BlbnNzaC1rZXktdjEAAAAABG5vbmUAAAAEbm9uZQAAAAAAAAABAAABlwAAAAdzc2gtcn
NhAAAAAwEAAQAAAYEA01//IEZR5EI0WyphzGsIq8NPasBI+Yth20tGCeFE7Cp8pFFEadAG
k1p+qu2SITmnm+qIxtP54q+TdZA60jMt+/wiHMMLTVh9ewT4cjj8PiIhdphIpERpY1pTJ9
7CZoOGVJsfEu0iWSKuEhC6qKuMJtfwPj1MfIM93NENtwZd2hGYH8qN+F2gUOuM1KS8mhL5
+4fgbagVPeQYl5k3pKnWmRwEQQ92t4p52mq6fLzpmDAxytg4z6qww/YyzQQt2LGsciqCiT
TQVhDI34CEUIC35D53QN84wALLCt+JqM1L12J6qcKHbenADq4XGkU823Fh6U6fjtAGWtKA
G/eW7X14JX6FyJvbUR2iECqTy9epKcjjPGCVpTBPF7nwuElXbkQl780meHPiczv8m+vehK
hN0vz5MM2W7UhmuckJTEC3N1HRYFcf0hC+lEltkGUYpsPFN2KtAfRZjuOcwfoFfAUJ4p+v
QbPMOpu2ZARwGCEPz5mIAHsZ5Tx5pcY72gyPOn8pAAAFkIiJCDiIiQg4AAAAB3NzaC1yc2
EAAAGBANNf/yBGUeRCNFsqYcxrCKvDT2rASPmLYdtLRgnhROwqfKRRRGnQBpNafqrtkiE5
p5vqiMbT+eKvk3WQOtIzLfv8IhzDC01YfXsE+HI4/D4iIXaYSKREaWNaUyfewmaDhlSbHx
LtIlkirhIQuqirjCbX8D49THyDPdzRDbcGXdoRmB/KjfhdoFDrjNSkvJoS+fuH4G2oFT3k
GJeZN6Sp1pkcBEEPdreKedpquny86ZgwMcrYOM+qsMP2Ms0ELdixrHIqgok00FYQyN+AhF
CAt+Q+d0DfOMACywrfiajNS9dieqnCh23pwA6uFxpFPNtxYelOn47QBlrSgBv3lu19eCV+
hcib21EdohAqk8vXqSnI4zxglaUwTxe58LhJV25EJe/NJnhz4nM7/Jvr3oSoTdL8+TDNlu
1IZrnJCUxAtzdR0WBXH9IQvpRJbZBlGKbDxTdirQH0WY7jnMH6BXwFCeKfr0GzzDqbtmQE
cBghD8+ZiAB7GeU8eaXGO9oMjzp/KQAAAAMBAAEAAAGAEP51z413xgdAmFfG9x1f3Bdeyj
FdbJq1KmFZ5y9yUB52WOujuXIdJTmwV2O0TPGKtTFc/8dJHt2I2HnZEM9GkizKPU+9F+HW
bM6QfvZv6TrrP9KsfHB3nKJFbz4smPtYEHNMQ0RHb60nG5K2vxrTsMfJq+dXv+b5UUiJdr
6PSxoBBgVN9rroSbk2YF5CP4zpBjz9YTOTSZ+ODpol7Bovg63J9cUdgVIjy9iq156ElVTC
nBFYN/H8NjUUDoGYggR+uD8QOFlgQzLAjn9SxrfZYhdZB1RZlOs5eyGLmn80bNMDDcZFxE
HxoUO78dNJMb2/sGnXPj/XVo7fn5dzKi32qLXuvF/xm8r/Xcd7fgJL8c9gzKM+lgJFfipC
ALWEcbpc3KYjwEf6i8qObYG50BIPccdSxGmmbzFbifzO8xRwEAZX6WSF+PbrM1iJZO3KOP
PgBJ0q4TcuZLWWoY7J0P0GwtsBYUexzdYGRTD3xNGWbC08Jp5Py2juAUHtPShZit7lAAAA
wGh8bmVBTPUZFtSPHfztCbstDltywIfP0Mr2s9//Q6HDzx3HGXIp+7utEhgEq4aF4Y/YdL
HX+CExHCiMQLqy9w6CBfXMo6M+YKTNGVt+x4qVh4Amsh1TYubLCzsc7tkL467/BYAqpAVl
KfqcsUl2NX7YDHgrrYDCX3u2zNn04wrzb33RCcoCFUxC2axcJXLmkHABm3JU6q7Qdcz6q8
Qbb6qyYoy9AOsV8P3xclMDrb2ty5lYW1/Z4MguYcrXUClnnwAAAMEA/c8H7XBal+7cXMzD
tmbUscSjcQNLHE/mnqrtAcg+J+W6hOv8Xo9+TXgUOST57LTmM7r+MAcNayE4UkvqreE3Bs
2VgH+0Z8jWHO7yCsQwGmCGNloMt7qwKJ9Vi6BJKg25JHqHjUXAFd77zZRG6+Pu8C2D/YgA
mpaGe3mC6Hddr3qUw3tHt+ku6q48HgPFM0OtbxALbR3x8tpgUPD8YcfeowvVXYa2wxK+5u
rc7r8i5piDm9pzhSxfmSQmQwSH5UD/AAAAwQDVMy2tOry/ZSFcLeJqdNXvonCEiERzH0Sz
90K3sa79ZevI2UlMGWZg5Uyz+nXl5XgOtNTRio8xkJ8r6HdCUzBTLxhNOiFiq3dr1LafUa
pSPxWNezpNkdMw/65qiKQw7u0cBizqUZxHQGyErZ9hYpcoDotqvKFohSQmY7D05PCP71aq
7XaQ8+f6qRn1BOhttsDveWD97R0JA/jmWauVzQthskEr4rHKh0LVznZ1KNM4N0WaSuyMC/
OoQfT8D9EmF9cAAAAVZXJhbWFAREVTS1RPUC1ENFA5UUc0AQIDBAUG
-----END OPENSSH PRIVATE KEY-----"
  REMOTE_HOST: "ec2-34-220-171-80.us-west-2.compute.amazonaws.com"
  REMOTE_USER: "ubuntu"
  REMOTE_TARGET: "/home/ubuntu"


name: node ci/cd

on: [push]

jobs:

  build:

  
    run-on: Ubuntu 22.04.1 LTS

    steps:

  
    - name: checkout the files
      uses: actions/checkout@v2

    - name: Install Node.js
      uses: actions/setup-node@v2
      with:
        node-version: '12.x'
    - name: install npm dependencies
      run: npm install
    - name: run build test
      run: npm run build --if-present
    - name: deploy to ec2
      uses: easingthemes/ssh-deploy@main
      env:
        SSH_PRIVATE_KEY: ${{ secrets.SERVER_SSH_KEY }}
        # ARGS: "-rltgoDzvO --delete"
        # SOURCE: "dist/"
        REMOTE_HOST: ${{ secrets.REMOTE_HOST }}
        REMOTE_USER: ${{ secrets.REMOTE_USER }}
        TARGET: ${{ secrets.REMOTE_TARGET }}
        # EXCLUDE: "/dist/, /node_modules/






